#!/usr/bin/env bash

for file in "$@"; do
    dir=$(dirname "${file}")
    basename=$(basename "${file}")
    output="${dir}/${basename%.*}-compressed.mp4"

    ffmpeg -i "${file}" -vcodec libx264 -crf 28 "${output}"
done
