#!/usr/bin/env bash

for file in "$@"; do
    dir=$(dirname "${file}")
    basename=$(basename "${file}")
    output="${dir}/${basename%.*}-720p.mp4"

    ffmpeg -i "${file}" -vf scale=-1:720 "${output}"
done
